taxane_nmr/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'taxane_nmr.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'nmr.views.home', name='home'),
    url(r'^search$', 'nmr.views.search', name='search'),
    url(r'^results/([0-9a-z]+)$', 'nmr.views.results', name='results'),
    url(r'^downloads$', 'nmr.views.downloads', name='downloads'),
    url(r'^browse$', 'nmr.views.browse', name='browse'),
    url(r'^record/([0-9]+)', 'nmr.views.record', name='record'),
    url(r'^help$', 'nmr.views.help', name='help'),
    url(r'^submit$', 'nmr.views.submit', name='submit'),
    url(r'^thank_you$', 'nmr.views.thank_you', name='thank_you'),
    #url(r'^admin/', include(admin.site.urls)),
)

nmr/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines for those models you wish to give write DB access
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from django.db import models
from django.core.urlresolvers import reverse
from random import randint
from datetime import datetime, timedelta
from hashlib import sha1
import re
from nmr import util
from django.conf import settings
from django.utils import timezone
from django.core.exceptions import ValidationError
from decimal import Decimal

def normalize_int_string(int_string):
    int_string = str(int_string) #will give horrible errors on python 2.7
    out = int_string
    m = re.match('^([0-9]+)(\.0*)?$',int_string)
    if m:
        out = m.group(1)
    return out

class Setting(models.Model):
    #this table stores settings that can be changed at runtime
    name = models.CharField(max_length=25, blank=False, unique=True, primary_key=True)
    value = models.CharField(max_length=50, blank=True)

class Record(models.Model):
    lab_num = models.CharField(max_length=25, blank=False, unique=True, help_text='The internal id assigned to the record by the Lange lab', primary_key=True)
    CAS_num = models.CharField(max_length=25, blank=True, help_text='Chemical Abstracts Service (CAS) number of the molecule')
    inchi_key = models.CharField(max_length=36, blank=False, help_text='InChIKey, 27 character identifier for the compound')
    inchi_standard = models.CharField(max_length=1000, blank=False, help_text='Standard InChI, a unique identifier for the structure')
    common_name = models.CharField(max_length=1000, blank=True)
    synonym = models.CharField(max_length=5000, blank=True)
    formula = models.CharField(max_length=1000, blank=True)
    molecular_weight = models.DecimalField(blank=False, max_digits=28, decimal_places=10)
    exact_mass = models.DecimalField(blank=False, max_digits=28, decimal_places=10)
    nmr_references = models.TextField()
    nmr_solvent = models.CharField(max_length=1000, blank=True)
    mhz = models.CharField(max_length=1000, blank=False)
    calibration = models.TextField()
    species = models.TextField()
    notes = models.TextField()
    proton_peaks = models.IntegerField(null=True)
    carbon_peaks = models.IntegerField(null=True)
    def get_absolute_url(self):
        return reverse('record', args=[self.lab_num])

class Submission(models.Model):
    submitter_name = models.CharField(max_length=1000, blank=False, help_text='Your name')
    submitter_email = models.EmailField(max_length=254, blank=False, help_text='Your e-mail address')
    
    common_name = models.CharField(max_length=1000, blank=True, help_text='The name most commonly used for the molecule.')
    synonym = models.CharField(max_length=5000, blank=True, help_text='Other names used for the molecule.')
    inchi = models.CharField(max_length=5000, blank=False, help_text='Full InChI, does not have to be Standard InChI.')
    formula = models.CharField(max_length=1000, blank=False, help_text='The molecule\'s chemical formula.')
    nmr_references = models.TextField(blank=True, help_text='Preferably in the style of the journal Cell. If a different reference is used for the proton spectrum as for the carbon spectrum, please put the proton reference first, then a semicolon, then the carbon reference.')
    nmr_solvent = models.CharField(max_length=1000, blank=True, help_text='If a different solvent was used for the proton spectrum as for the carbon spectrum, please put the proton solvent first, then a semicolon, then the carbon solvent.')
    mhz = models.DecimalField(max_length=1000, max_digits=20, decimal_places=5, blank=True, null=True, help_text='Proton NMR mHz.')
    calibration = models.CharField(max_length=1000, blank=True, help_text='What was the basis for shift calibration.')
    notes = models.TextField(blank=True, help_text='Additional notes about the spectra or molecule.')
    proton_spectrum = models.TextField(blank=True, help_text='Assignments, shifts, peak types, and coupling constants for proton the proton spectrum.')
    carbon_spectrum = models.TextField(blank=True, help_text='Assignments, and shifts for the carbon spectrum.')

class Carbon(models.Model):
    record = models.ForeignKey(Record)
    position = models.CharField(max_length=1000, blank=True)
    ppm = models.DecimalField(blank=False, max_digits=20, decimal_places=5)
    order=models.PositiveSmallIntegerField(blank=False)
    def save(self, *args, **kwargs):
        #convert decimal values into flat integers
        self.position = normalize_int_string(self.position)
        super(Carbon, self).save(*args, **kwargs)
    class Meta:
        unique_together = ("record", "order")

class Proton(models.Model):
    record = models.ForeignKey(Record)
    position = models.CharField(max_length=1000, blank=True)
    ppm = models.DecimalField(blank=False, max_digits=20, decimal_places=5)
    peak_type = models.CharField(max_length=20, blank=True)
    peak_type_search_format = models.TextField(max_length=20, blank=True)
    order=models.PositiveSmallIntegerField(blank=False)
    class Meta:
        unique_together = ("record", "order")
    def save(self, *args, **kwargs):
        #convert decimal values into flat integers
        self.position = normalize_int_string(self.position)
        self.peak_type = self.peak_type.strip()
        self.peak_type_search_format = util.format_peak_type_for_search(self.peak_type)
        super(Proton, self).save(*args, **kwargs)

class ProtonCoupling(models.Model):
    proton = models.ForeignKey(Proton)
    j = models.DecimalField(blank=False, max_digits=20, decimal_places=5)
    def __str__(self):
        return '%s' % (self.j,)

    
class Query(models.Model):
    #Basically, how the query will work is if you enter data for a particular field, it will use that data to search
    ALIGNMENT_ALGORITHM_CHOICES = ((x,x) for x in ('munkres'))
    ALIGNMENT_SCORING_CHOICES = (('PURE', 'Pure'),
                                ('MIXTURE', 'Mixture'))
    
    
    proton_shift_tolerance = models.FloatField(blank=True, null=True)
    carbon_shift_tolerance = models.FloatField(blank=True, null=True)
    coupling_constant_tolerance = models.FloatField(blank=True, null=True)
    exact_mass = models.CharField(blank=True, null=True, max_length=5000)
    exact_mass_tolerance = models.DecimalField(blank=True, null=True, max_digits=20, decimal_places=10)
    chemical_formula = models.CharField(max_length=5000, blank=True)
    hash = models.CharField(max_length=40, unique=True, primary_key=True) #40 is the length of a sha1 hash hex
    alignment_algorithm = models.CharField(max_length=20, blank=False, default='munkres', choices=ALIGNMENT_ALGORITHM_CHOICES)
    alignment_scoring = models.CharField(max_length=10, blank=False, default='PURE', choices=ALIGNMENT_SCORING_CHOICES) #If PURE, penalize an alignment score based on max(query_peaks, target_peaks). If MIXTURE, penalize alignment score based on target_peaks.
    name = models.CharField(max_length=5000, blank=True)
    
    proton_nmr = models.TextField(blank=True) #three columns, ppm, peak type, J (Hz)
    carbon_nmr = models.TextField(blank=True) #one column, peak type
    def clean(self):

        if self.exact_mass != None and self.exact_mass != "":
            try: 
                for num in self.exact_mass.split(";"):
                    Decimal(num.strip())
            except Exception:
                raise ValidationError('Invalid exact mass: should be semicolon separated decimal numbers, e.g.: "342.74;1456.7", or "342.74"')
        

    def save(self, *args, **kwargs):
        #generate hash for search
        #x = 
        #print(x)
        #print(type(x))
        #print(type(x.encode('ascii')))
        #print(x.encode('ascii'))
        #print("".join([str(randint(0,9)) for x in range(4)]))
        bytes = datetime.now().isoformat() + "".join([str(randint(0,9)) for x in range(4)])
        bytes = bytes.encode('ascii')
        self.hash = sha1(bytes).hexdigest()
        #normalize_chemical_formulas
        formulas = [util.normalize_formula(x.strip()) for x in self.chemical_formula.split(';')]
        self.chemical_formula = ";".join([x for x in formulas if x != ""])
        
        
        self.proton_nmr = self.proton_nmr.strip()
        self.carbon_nmr = self.carbon_nmr.strip()
        #print(self.hash)
        super(Query, self).save(*args, **kwargs)


class Result(models.Model):
    query = models.ForeignKey(Query, unique=True)
    hash = models.CharField(max_length=40, unique=True, primary_key=True) #40 is the length of a sha1 hash hex
    data = models.BinaryField(blank=True) # a pickled output of the query results (can't be json because it contains decimal fields)
    expires = models.DateTimeField(blank=False)
    errors = models.BinaryField(blank=True) # a pickled list of errors encountered during the search (could be json, but I'm trying to stay consistent)
    def get_absolute_url(self):
        return reverse('result', args=[self.hash])
    
    def save(self, *args, **kwargs):
        self.expires = timezone.now() + timedelta(days = settings.DAYS_TO_KEEP_RESULTS)
        super(Result, self).save(*args, **kwargs)

nmr/forms.py
from django import forms
from nmr.models import Query, Submission


query_widgets = {'exact_mass': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'exact_mass_tolerance': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'chemical_formula': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'proton_shift_tolerance': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'carbon_shift_tolerance': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'coupling_constant_tolerance': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'alignment_scoring': forms.Select(attrs={'class':"form-control"}),
            'proton_nmr': forms.Textarea(attrs={'class':"form-control"}),
            'carbon_nmr': forms.Textarea(attrs={'class':"form-control"}),
            'name':forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            }
query_fields = ('name','exact_mass', 'exact_mass_tolerance', 'chemical_formula', 'proton_shift_tolerance', 'carbon_shift_tolerance', 'coupling_constant_tolerance', 'alignment_scoring', 'proton_nmr', 'carbon_nmr')
#query_widgets = {x: 
class QueryForm(forms.models.ModelForm):
    
    class Meta:
        model = Query
        fields = query_fields
        widgets = query_widgets
        labels = {
            'name':'Name','proton_shift_tolerance': 'Proton Shift Tolerance', 'carbon_shift_tolerance': 'Carbon Shift Tolerance', 'coupling_constant_tolerance': 'Coupling Constant Tolerance', 'exact_mass': 'Exact Mass', 'chemical_formula': 'Chemical Formula', 
            'proton_nmr': 'Proton NMR', 'carbon_nmr': 'Carbon NMR', 'alignment_scoring': 'Alignment Scoring'
        }
        
        
submit_widgets = {
            'submitter_name': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'submitter_email': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'common_name': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'synonym': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'inchi': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'formula': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'nmr_references': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'nmr_solvent': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'mhz': forms.NumberInput(attrs={'class':"form-control", 'type':'number'}),
            'calibration': forms.TextInput(attrs={'class':"form-control", 'type':'text'}),
            'notes': forms.Textarea(attrs={'class':"form-control"}),
            'proton_spectrum': forms.Textarea(attrs={'class':"form-control"}),
            'carbon_spectrum': forms.Textarea(attrs={'class':"form-control"}),
            }

class SubmitForm(forms.models.ModelForm):

    class Meta:
        model = Submission
        #fields = query_fields
        widgets = submit_widgets
        labels = {
                'nmr_references' : 'NMR references',
                'nmr_solvent' : 'NMR solvent',
                'inchi': 'InChI',
                'mhz': 'mHz'
            }
            # 'proton_shift_tolerance': 'Proton Shift Tolerance', 'carbon_shift_tolerance': 'Carbon Shift Tolerance', 'coupling_constant_tolerance': 'Coupling Constant Tolerance', 'exact_mass': 'Exact Mass', 'chemical_formula': 'Chemical Formula', 
            # 'proton_nmr': 'Proton NMR', 'carbon_nmr': 'Carbon NMR',
        # }

nmr/templates/nmr/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Spektraris NMR</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="http://fonts.googleapis.com/css?family=Noto+Serif&subset=latin,greek" rel='stylesheet' type='text/css'>
        <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet" media="screen">
        <script type="text/javascript" src="{% static "jquery-2.0.3.min.js" %}"></script>
        <script type="text/javascript" src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
        <link href="{% static "base.css" %}" rel="stylesheet" media="screen">
        <style>
            body { background: url("{% static "media/white_wall_hash.png" %}") repeat scroll 0% 0% transparent; }
        </style>
        {% block header %}
        {% endblock %}
    </head>
    <body>
        <div id="body_content" class="container">
            <div id="header">
                <div class="row">
                    <div class="col-md-6">
                        <h1>Spektraris NMR</h1>
                    </div>
                </div>
                <ul class="nav nav-pills nav-justified" id="mgr_main_main_menu_bar">
                    <li class= "{% if "Home" in page %} active {% endif %}"><a href="{% url "nmr.views.home"%}">Home</a></li>
                    <li class= "{% if "Search" in page %} active {% endif %}"><a href="{% url "nmr.views.search"%}">Search</a></li>
                    <li class= "{% if "Browse" in page %} active {% endif %}"><a href="{% url "nmr.views.browse"%}">Browse</a></li>
                    <li class= "{% if "Downloads" in page %} active {% endif %}"><a href="{% url "nmr.views.downloads"%}">Downloads</a></li>
                    <li class= "{% if "Submit" in page %} active {% endif %}"><a href="{% url "nmr.views.submit"%}">Submit</a></li>
                    <li class= "{% if "Help" in page %} active {% endif %}"><a href="{% url "nmr.views.help"%}">Help</a></li>
                </ul>
            </div>
            {% block main_area %}
            {% endblock %}
            <div id="footer">
                <div class="row">
                    <div class="col-md-12">
                    <hr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <img src="{% static "wsu_logo.png" %}" alt="WSU logo" id="wsu_logo"/>
                    </div>
                    <div class="col-md-3">
                        Copyright © {{ year }}
                    </div>
                    <div class="col-md-6">
                        The Spektraris NMR database is developed and hosted by the Lange laboratory at WSU. CAS Registry Number is a Registered Trademark of the American Chemical Society.
                    </div>
                </div>
            </div>
        </div>
    </body>
{% block after_body %}
{% endblock %}
</html>

nmr/templates/nmr/downloads.html
{% extends 'nmr/base.html' %}
{% load staticfiles %}
{% block main_area %}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading"><h4>Downloads and Links</h4></div>
        <table class="table">
        <thead>
            <tr>
                <th>File</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
                <tr>
                    <td><a href="{% static "downloads/database_flatfiles.zip" %}">Database flat files</a></td>
                    <td><p>All of the compound data and spectra from this website, condensed into a convenient set of tab separated text files.</p></td>
                </tr>
                <tr>
                    <td><a href="{% static "downloads/taxane_nmr_spectra.zip" %}">Complete Spectra</a></td>
                    <td><p>Varian FID, JCAMP-DX, and nmrML files for NMR spectra of Taxol, 2-deacetyl baccatin IV, Baccatin III, N-Acetyl-N-debenzoyltaxol, 13-Acetyl-9-dihydrobaccatin III, baccatin IV, Taxol D, Taxol B, and Taxol C.</p></td>
                </tr>
                <tr>
                    <td><a href="https://bitbucket.org/seanrjohnson/taxane_nmr/src">Source code</a></td>
                    <td><p>A link to the source code for this very website. The website was built using Python 3.3 and Django 1.6, with a few additional dependencies.</p></td>
                </tr>
                <tr>
                    <td><a href="">LC-MS data</a></td>
                    <td><p>Coming soon! LC retention times and MS and MS<sup>2</sup> spectra for a selected subset of taxanes.</p></td>
                </tr>
        </tbody>
        </table>
    </div>
</div>
{% endblock %}

nmr/templates/nmr/home.html
{% extends 'nmr/base.html' %}
{% block main_area %}
<p>
Welcome to the Spektraris NMR database: a searchable collection of proton and carbon NMR spectra currently focusing on diterpenoid natural products related to the important drug paclitaxel. The more than 400 spectra from more than 200 compounds in this database were manually transcribed from the literature. You use the database as a tool to aid structure elucidation by searching spectra of unknown taxanes.
</p>

<p>
Many of the spectra are currently, or will soon be available on <a href="http://nmrshiftdb.nmr.uni-koeln.de/">NMRShiftDB</a>, so you can also search for unknown taxane spectra there.
</p>

<p>
Reference: <a href="http://www.ncbi.nlm.nih.gov/pubmed/25534952">Fischedick et al. 2015</a>
</p>
{% endblock %}

nmr/templates/nmr/submit.html
{% extends 'nmr/base.html' %}
{% block main_area %}
<h3>Submit Spectra</h3>
<p>
To submit a compound for inclusion in the database, simply fill out this form, and click submit. The format of the spectral data should be similar to as the format in the search form, except that the first column should have peak name, and the other columns will be shifted one to the left. The information will be sent to an administrator for review. If you are submitting spectra to Spektraris, consider also submitting them to <a href="http://nmrshiftdb.nmr.uni-koeln.de/">NMRShiftDB</a>.
</p>
<hr />
<form method="POST" action="" class="form-horizontal" role="form" id="nmr_search_form">
  {% csrf_token %}
    <div class="form-super-group">
        <div class="form-group {% if form.submitter_name.errors or form.submitter_email.errors %}has-error{%endif%}">
            <label for="id_submitter_name" class="col-sm-2 control-label">{{ form.submitter_name.label}}</label>
            <div class="col-sm-2">
                {{ form.submitter_name }}
            </div>
            <div class="col-sm-3">
            {{form.submitter_name.help_text}}
            </div>
            <div class="col-sm-3">
                <ul class="list-inline">
                {% for error in form.submitter_name.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
        <div class="form-group {% if form.submitter_email.errors or form.submitter_email.errors %}has-error{%endif%}">
            <label for="id_submitter_email" class="col-sm-2 control-label">{{ form.submitter_email.label}}</label>
            <div class="col-sm-2">
                {{ form.submitter_email }}
            </div>
            <div class="col-sm-3">
            {{form.submitter_email.help_text}}
            </div>
            <div class="col-sm-3">
                <ul class="list-inline">
                {% for error in form.submitter_email.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="form-super-group">
        <div class="form-group {% if form.common_name.errors or form.submitter_email.errors %}has-error{%endif%}">
            <label for="id_common_name" class="col-sm-2 control-label">{{ form.common_name.label}}</label>
            <div class="col-sm-2">
                {{ form.common_name }}
            </div>
            <div class="col-sm-3">
            {{form.common_name.help_text}}
            </div>
            <div class="col-sm-3">
                <ul class="list-inline">
                {% for error in form.common_name.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
        <div class="form-group {% if form.synonym.errors or form.synonym.errors %}has-error{%endif%}">
            <label for="id_synonym" class="col-sm-2 control-label">{{ form.synonym.label}}</label>
            <div class="col-sm-2">
                {{ form.synonym }}
            </div>
            <div class="col-sm-3">
            {{form.synonym.help_text}}
            </div>
            <div class="col-sm-3">
                <ul class="list-inline">
                {% for error in form.synonym.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
        <div class="form-group {% if form.inchi.errors or form.inchi.errors %}has-error{%endif%}">
            <label for="id_inchi" class="col-sm-2 control-label">{{ form.inchi.label}}</label>
            <div class="col-sm-2">
                {{ form.inchi }}
            </div>
            <div class="col-sm-3">
            {{form.inchi.help_text}}
            </div>
            <div class="col-sm-3">
                <ul class="list-inline">
                {% for error in form.inchi.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
        <div class="form-group {% if form.formula.errors or form.formula.errors %}has-error{%endif%}">
            <label for="id_formula" class="col-sm-2 control-label">{{ form.formula.label}}</label>
            <div class="col-sm-2">
                {{ form.formula }}
            </div>
            <div class="col-sm-3">
            {{form.formula.help_text}}
            </div>
            <div class="col-sm-3">
                <ul class="list-inline">
                {% for error in form.formula.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
        <div class="form-group {% if form.nmr_references.errors or form.nmr_references.errors %}has-error{%endif%}">
            <label for="id_nmr_references" class="col-sm-2 control-label">{{ form.nmr_references.label}}</label>
            <div class="col-sm-2">
                {{ form.nmr_references }}
            </div>
            <div class="col-sm-3">
            {{form.nmr_references.help_text}}
            </div>
            <div class="col-sm-3">
                <ul class="list-inline">
                {% for error in form.nmr_references.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
        <div class="form-group {% if form.nmr_solvent.errors or form.nmr_solvent.errors %}has-error{%endif%}">
            <label for="id_nmr_solvent" class="col-sm-2 control-label">{{ form.nmr_solvent.label}}</label>
            <div class="col-sm-2">
                {{ form.nmr_solvent }}
            </div>
            <div class="col-sm-3">
            {{form.nmr_solvent.help_text}}
            </div>
            <div class="col-sm-3">
                <ul class="list-inline">
                {% for error in form.nmr_solvent.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
        <div class="form-group {% if form.mhz.errors or form.mhz.errors %}has-error{%endif%}">
            <label for="id_mhz" class="col-sm-2 control-label">{{ form.mhz.label}}</label>
            <div class="col-sm-2">
                {{ form.mhz }}
            </div>
            <div class="col-sm-3">
            {{form.mhz.help_text}}
            </div>
            <div class="col-sm-3">
                <ul class="list-inline">
                {% for error in form.mhz.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
        <div class="form-group {% if form.calibration.errors or form.calibration.errors %}has-error{%endif%}">
            <label for="id_calibration" class="col-sm-2 control-label">{{ form.calibration.label}}</label>
            <div class="col-sm-2">
                {{ form.calibration }}
            </div>
            <div class="col-sm-3">
            {{form.calibration.help_text}}
            </div>
            <div class="col-sm-3">
                <ul class="list-inline">
                {% for error in form.calibration.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="form-super-group">
        <div class="form-group {% if form.notes.errors or form.submitter_email.errors %}has-error{%endif%}">
            <label for="id_notes" class="col-sm-2 control-label">{{ form.notes.label}}</label>
            <div class="col-sm-4">
                {{ form.notes }}
            </div>
            <div class="col-sm-2">
            {{form.notes.help_text}}
            </div>
            <div class="col-sm-2">
                <ul class="list-inline">
                {% for error in form.notes.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="form-super-group">
        <div class="form-group {% if form.proton_spectrum.errors or form.submitter_email.errors %}has-error{%endif%}">
            <label for="id_proton_spectrum" class="col-sm-2 control-label">{{ form.proton_spectrum.label}}</label>
            <div class="col-sm-4">
                {{ form.proton_spectrum }}
            </div>
            <div class="col-sm-2">
            {{form.proton_spectrum.help_text}}
            </div>
            <div class="col-sm-2">
                <ul class="list-inline">
                {% for error in form.proton_spectrum.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="form-super-group">
        <div class="form-group {% if form.carbon_spectrum.errors or form.submitter_email.errors %}has-error{%endif%}">
            <label for="id_carbon_spectrum" class="col-sm-2 control-label">{{ form.carbon_spectrum.label}}</label>
            <div class="col-sm-4">
                {{ form.carbon_spectrum }}
            </div>
            <div class="col-sm-2">
            {{form.carbon_spectrum.help_text}}
            </div>
            <div class="col-sm-2">
                <ul class="list-inline">
                {% for error in form.carbon_spectrum.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>
</form>

{% endblock %}

nmr/templates/nmr/thank_you.html
{% extends 'nmr/base.html' %}
{% block main_area %}
<h3>Thank you for your submission!</h3>
<p>
If it is not added to the database in a timely fashion, don't hesitate to send a nagging email to one of the contacts listed on the "Help" page.
</p>

{% endblock %}